app = 'rs-de-clockout'
primary_region = 'fra'

[build]

[env]
  CLOCKOUT_DATA_DIR = '/data/sync'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = 'clockout_data'
  destination = '/data'
